services:
  - docker

language: python
python:
  - 2.7
  - 3.8

cache:
  pip: true

branches:
  only:
    - gh-pages
    - /.*/

before_script:
  - pip install -U pip setuptools wheel
  - pip install cwltool cwltest html5lib

script:
  - make RUNNER=cwltool unittest-examples
