sudo: required
services:
  - docker

language: python
python:
  - 2.7
  - 3.6

branches:
  only:
    - gh-pages
    - /.*/

before_script:
  - git clone https://github.com/common-workflow-language/cwltool.git cwltool && pip install ./cwltool
  - git clone https://github.com/common-workflow-language/cwltest.git cwltest && pip install ./cwltest

script:
  - make RUNNER=cwltool unittest-examples
