language: python
python:
  - 2.7
  - 3.6

before_script:
  - git clone https://github.com/common-workflow-language/cwltool.git cwltool && pip install ./cwltool
  - git clone https://github.com/common-workflow-language/cwltest.git cwltest && pip install ./cwltest

script:
  - make RUNNER=cwltool unittest-examples
